import { Inter } from "next/font/google";
import "../../../src/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dashboard",
  description: "Generated by Finance Tracker APP",
};

export default function DashBoardLayout({
  children,
  balanceSheet,
  budget,
  expenses,
  samplegetstaticprops,
  notstaticprops
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div style={{ display: 'flex' }}>
          <div style={{ display: 'flex', flexDirection: 'row', padding:'50px' }}>
            <div style={{padding:'20px' }}>{budget}</div>
            <div style={{padding:'20px' }}>{expenses}</div>
            <div style={{padding:'20px' }}>{balanceSheet}</div>
            <div style={{padding:'20px' }}>{samplegetstaticprops}</div>
            <div style={{padding:'20px' }}>{notstaticprops}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
